### ISSUE TITLE
Initial free call distribution methods

### ISSUE THREAD

**Issue by jakehemmerle** [entropyxyz/entropy-core#203]
## Overview

We want to distribute free calls to users to make free actions on the network. We can use any number of Sybil-resistant ways to do this, including:
- Distributing NFTs to early users, which can be used to get some reoccuring free calls or free calls from a faucet (authentication via NFT).
- minting and distributing 'coupons' (via Discord, whatever) which can be cashed-in for some free calls

## Todo

- [x] Discuss with product additional methods (NFT idea above)
- [ ] Agree upon on what method(s) we want to use
- [ ] Write a technical proposal for implementing the methods
- [ ] Feature and tests for

---

### Misc notes on implementation

For way 2, initially I wanted to just generate a list of 16byte strings where the hashes of each get put on-chain and users send them in a TX to redeem them. Jesse brought up a great point that the mempool could be listened to and the credit strings could be nabbed and submitted with a higher tx fee. This needs to be solved before implementing.

**Comment by HCastano** [comment]
We removed all this.
